README.md

* Changed Url's branch query parameter from `gh-pages` to `master`

Fixes #8 : readme.md will now show correct build status

---

README.md

* Changed url branch from `gh-pages` to `master`.
* To show proper codecov badge

Updated Readme.md CodeCoverage status Url

---

.travis.yml
deploy.sh
src/app/feed/feed.component.html
src/app/feed/feed.component.scss
src/app/feed/feed.component.spec.ts
src/app/feed/feed.component.ts

* The travis auto deploy script will only work after `deploy key` setup.
* The feed view is in very basic form.

Travis auto-deploy script and integration search results displaying views

---

deploy.sh
src/index.html

* Also needs a 404.html in gh-pages

Fixes #21:Added script to handle route in gh-pages

---

deploy.sh

* Changed the file removal to "find and delete" excluding 
* Deploy only if changes have occured in the build files (ignore readme changes etc)

Fixes #21: Improved deploy script

---

deploy.sh
src/index.html

Removed loading text which appeared while the app loaded

Fixes #22: No loading text displayed

---

404.html

Fixes #21: New 404.html for proper redirect

---

package.json
src/app/feed/feed-card/feed-card.component.html
src/app/feed/feed-card/feed-card.component.scss
src/app/feed/feed-card/feed-card.component.spec.ts
src/app/feed/feed-card/feed-card.component.ts
src/app/feed/feed.component.html
src/app/feed/feed.component.scss
src/app/feed/feed.component.spec.ts
src/app/feed/feed.component.ts
src/app/feed/feed.module.ts
src/app/shared/services/search/search.service.ts
src/index.html

Fixes #23
* Basic card design with simlplistic layout, similar to google and twitter.
* Likify the text links

Fixes #23 : Simple card design

---

src/app/feed/feed-header/feed-header.component.html
src/app/feed/feed-header/feed-header.component.scss

Fixes #34 
* Heights of header aligned.
* Outline and shadow removed when input box is in focus
* Removed search button from the tab order of the DOM

Fixes #34: No box shadow on search bar

---

src/app/feed/feed-header/feed-header.component.scss

Fixes #34: Header and search-bar heights adjust

---

src/app/home/home.component.html
src/app/home/home.component.ts

Fixes #38 
* Changed the event from keypress to keydown
* Escaped the undesired keys.

Fixes #38: Added key escaping for firefox

---

src/app/home/home.component.ts

Fixes #45 
Search bar focuses when home page is loaded

Fixes #45: Focus on the search bar when page loads

---

src/app/home/home.component.ts

minor patch for #38 
* Cmd/ctrl/alt + Key

Fixes #38: (minor) Escaping some key cominations

---

src/app/footer/footer.component.html
src/app/footer/footer.module.ts

Fixes the bugs in #27 
* Links now open in thw same tab
* The links not clicking problem solved

Fixes #27: Links opening in same tab

---

src/app/feed/feed-not-found/feed-not-found.component.html
src/app/feed/feed-not-found/feed-not-found.component.scss
src/app/feed/feed-not-found/feed-not-found.component.spec.ts
src/app/feed/feed-not-found/feed-not-found.component.ts
src/app/feed/feed.component.html
src/app/feed/feed.component.scss
src/app/feed/feed.component.spec.ts
src/app/feed/feed.component.ts
src/app/feed/feed.module.ts

Fixes #52 
* showing information when no results are found
* also bottom bar is adjusted accordingly

Fixes #52: Info on no results found

---

src/app/feed/feed-header/feed-header.component.ts

Noticed that the name of the image in the assets folder was named differently than the image in the line.  Maybe look at changing to match.

Match image name/url to copy the name of the image in the assets folder.

---

.travis.yml
src/app/app.module.ts
src/app/feed/feed-card/feed-card.component.ts
src/app/feed/feed.component.html
src/app/feed/feed.component.spec.ts
src/app/feed/feed.component.ts
src/app/home/home.component.spec.ts
src/app/shared/classes/index.ts
src/app/shared/classes/search/api-response.spec.ts
src/app/shared/classes/search/api-response.ts
src/app/shared/classes/search/index.ts
src/app/shared/index.ts
src/app/shared/services/search/search.service.ts
src/environments/environment.prod.ts
src/main.ts
tslint.json

* Typescript classes for the request objects.
* Added linting to the Travis tests.

Implements #64 : Typescript classes of Api Response

---

src/app/terms/terms.component.html
src/app/terms/terms.component.scss
src/app/terms/terms.component.spec.ts
src/app/terms/terms.module.ts

issue [#73](https://github.com/fossasia/loklak_search/issues/73)
@mariobehling please check this.

implemented terms page

---

src/app/terms/terms.component.html
src/app/terms/terms.component.scss

fix issue  #73 
sample site can be viewed [here](https://pranayyelugam.github.io/loklak_search/terms) 
@mariobehling  check this.

aligned heading and adjusted width

---

src/app/contact/contact.component.html

* The application is not loading right now due to error in template.
* The error was wrongly closed `a tag`

Fixes #90: Fixing the parsing error in application loading

---

src/app/terms/terms.component.html

* Fixed error in terms.component.html
* The error was same as in contact.component.html
* This fixes #90 completely

Fixes #90: Template parse errors

---

src/app/about/about.component.html

The links (open data, open source etc) properly to search results

Fixes #96: redirecting bug from about component

---

README.md

Issue #132 Resolved
Task: https://codein.withgoogle.com/dashboard/task-instances/4868987345174528/

Improved Instruction for Deploying with Github Pages

---

angular-cli.json
src/app/feed/feed-footer/feed-footer.component.html
src/app/feed/feed-footer/feed-footer.component.scss
src/app/reducers/api-response.ts
src/app/reducers/index.ts

* Using flexbox, simplified classnames and scss style class nesting.
* Variable name changes (minor)
* Updated `angular-cli.json`.

Fixes(minor): to feed footer (hashtag) component

---

README.md
angular-cli.json
src/app/feed/feed-card/feed-card.component.html
src/app/feed/feed-card/feed-card.component.scss
src/app/feed/feed-card/feed-card.component.ts
src/app/feed/feed-footer/feed-footer.component.html
src/app/feed/feed-footer/feed-footer.component.scss
src/app/reducers/api-response.ts
src/app/reducers/index.ts

Fixes #105 
You can see a preview here: https://heredroky.github.io/loklak_search/loklak_searchsearch?query=obama
@hemantjadon @mariobehling

Adding lightbox

---

src/app/home/home.component.html
src/app/home/home.component.scss

@hemantjadon Here's the one commit for the requisite change. Kindly merge the same. Thank You.

#93 home-page design changes

---

src/app/feed/feed-card/feed-card.component.html
src/app/feed/feed-card/feed-card.component.scss

gh-pages :- https://achint08.github.io/loklak_search/

Fixed #141: Modified design for lighbox with some more design features

---

src/app/feed/feed-card/feed-card.component.scss

For Screen size less than 600 pixels the light box will adjust like this. Kindly check and review.
gh-pages :- https://achint08.github.io/loklak_search/

 Fixes #105 : Made Lightbox Responsive

---

src/app/feed/feed-card/feed-card.component.html
src/app/feed/feed-card/feed-card.component.ts
src/app/feed/feed-linker/feed-linker.component.html
src/app/feed/feed-linker/feed-linker.component.ts

This PR must be able to resolve the issue depicted in #144 and close it.

Fix #144: Lightbox pops up when clicking on link

---

src/app/about/about.component.html

Changes as demanded by @mariobehling .

Fixes #60 :- Minor changes to about pages

---

package.json
sass-lint.yml

SCSS linter has been added as per issue #158.

#158 Added scss lint

---

src/app/feed/feed-pagination/feed-pagination.component.scss

Changes are live at https://uttu357.github.io/loklak_search/search?query=javascript
Closes #163

Fix #163 : Simplify Search More style

---

src/app/feed/feed-card/feed-card.component.html

I have added a feature where the user will be able to interact with
tweets from within the loklak search engine! Now, users can like,
retweet and reply easily.
Solves issue: #161

Made the reply, retweet and like work

---

src/app/home/home.component.html

#175 Added an information line below the search box

Fixes #175

---

src/app/feed/feed-header/feed-header.component.scss

The search button and search input field on the results page are
now vertically aligned.
fixes #167

Vertically aligning the search button and search input field

---

src/app/feed/feed-card/feed-card.component.ts

- Also changes 'h' to 'h ago'.
Closes #182

Fix #182: Display tweet time on initializing

---

src/app/footer/footer.component.html

Solve the [issue](https://github.com/fossasia/loklak_search/issues/171) as mentioned

Improving Footer #171

---

src/app/feed/feed-header/feed-header.component.html
src/app/feed/feed-header/feed-header.component.scss
src/app/feed/feed-header/feed-header.component.ts
src/app/home/home.component.spec.ts
src/app/home/home.component.ts
src/app/navbar/navbar.component.html
src/app/navbar/navbar.component.scss

Fixes #186 : logo change

---

src/app/actions/api.ts
src/app/feed/feed-footer/feed-footer.component.ts
src/app/feed/feed-header/feed-header.component.scss
src/app/feed/feed.component.html
src/app/feed/feed.component.scss
src/app/feed/feed.component.spec.ts
src/app/feed/feed.component.ts
src/app/feed/feed.module.ts
src/app/feed/info-box/info-box.component.html
src/app/feed/info-box/info-box.component.scss
src/app/feed/info-box/info-box.component.specs.ts
src/app/feed/info-box/info-box.component.ts
src/app/home/home.component.scss
src/app/models/api-response.ts
src/app/reducers/api-response.ts
src/app/reducers/index.ts
src/app/services/search.service.ts

Need help in the following
- Convert the respective lists into tabs
- Add queryParams for the Hashtags and Mentions
- Content doesn't change when the input changes
- Mobile View design needs to be added
site hosted at [rishiraj.co/loklak_search](http://rishiraj.co/loklak_search)
Please have a look @hemantjadon and @mariobehling

Added InfoBox #92

---

src/app/feed/feed-card/feed-card.component.scss

https://brainbuzzer.github.io/loklak_search/
Fixes #105

Make Lightbox Responsive

---

src/app/feed/feed-card/feed-card.component.html

Fixes Twitter link.
Closes #197

Fix #197: Fix twitter link

---

src/app/feed/feed.component.html
src/app/feed/feed.component.scss
src/app/feed/info-box/info-box.component.html
src/app/feed/info-box/info-box.component.scss

-Also fix indentation in infobox.component.html
Changes live at https://uttu357.github.io/loklak_search/search?query=node
Closes #196

Fix #196: Implement google theme on search page

---

src/app/home/home.component.html
src/app/home/home.component.scss

Please review the following. @mariobehling

Fixed  Home Page Help Text #204 

---

src/app/feed/info-box/info-box.component.ts

Fixes issue #200. Live link [here](https://oanarosca.github.io/loklak_search).

Update sidebar on every search

---

src/app/services/search.service.ts

fixes #210 :-20 feeds

---

src/app/feed/info-box/info-box.component.html

Closes issue #200 @mariobehling

Made links open in the same tab

---

src/app/feed/info-box/info-box.component.html
src/app/feed/info-box/info-box.component.ts

Now clicking on the links in the infobox searches it correspondingly by `#hashtagname, from:username etc.
`

Query linked with search params #221

---

src/app/feed/feed-card/feed-card.component.html
src/app/feed/feed-lightbox/feed-lightbox.component.html

Fixes #223 : Tweet names shows tweets on loklak.net .

---

src/app/footer/footer.component.html

https://github.com/fossasia/loklak_search/issues/226

Added code in footer

---

src/app/feed/feed-card/feed-card.component.html
src/app/feed/feed-card/feed-card.component.ts
src/app/feed/feed.module.ts
src/app/feed/info-box/info-box.component.html
src/app/feed/info-box/info-box.component.ts
src/app/shared/in-viewport.directive.ts

Image will load now only when on screen.
[Link](https://achint08.github.io/loklak_search/)

Fixes #240 :- Load image when required

---

src/app/feed/feed-header/feed-header.component.scss
src/app/home/home.component.html
src/app/home/home.component.scss
src/app/home/home.component.spec.ts
src/app/home/home.component.ts
src/index.html
src/styles.scss
src/styles/partials/_typography.scss

- Added Roboto font to all the screens.
- Changed logo design as in the screenshot.
Partly fixes: #226

#226 fixes on font and logo design

---

src/app/feed/feed.component.html
src/app/feed/feed.component.scss

Show a loading bar while searching #172

---

src/app/app.module.ts
src/app/effects/api-suggest.effects.ts
src/app/feed/feed-header/feed-header.component.html
src/app/feed/feed-header/feed-header.component.scss
src/app/feed/feed-header/feed-header.component.ts
src/app/feed/feed.component.html
src/app/feed/feed.component.spec.ts
src/app/feed/feed.component.ts
src/app/home/home.component.ts
src/app/models/api-suggest.ts
src/app/reducers/index.ts
src/app/reducers/suggest-response.ts
src/app/services/index.ts
src/app/services/suggest.service.ts

Implements auto completion feature. Checkout it out [here](https://achint08.github.io/loklak_search/).
Kindly review and correct me. :)
One more I would like to have a view is that I haven't use datalist element to show the suggestions reason being that the new suggesstion data was not displayed in that case. Any suggesstion?

Implements #29 : Adds autocompletion suggestion feature

---

src/app/feed/feed.component.html
src/app/feed/feed.component.spec.ts
src/app/feed/feed.component.ts
src/app/feed/info-box/info-box.component.ts
src/app/feed/user-info-box/user-info-box.component.html
src/app/feed/user-info-box/user-info-box.component.scss
src/app/feed/user-info-box/user-info-box.component.ts
src/app/models/api-user-response.ts
src/app/reducers/api-user-response.ts
src/app/reducers/index.ts
src/app/services/user.service.ts

https://uttu357.github.io/loklak_search/search?query=from%3Afossasia
Closes #245 
@mariobehling Please review. :)

Fix #245: Add followers and following in user box

---

src/app/feed/feed.component.html
src/app/feed/user-info-box/user-info-box.component.html

Checkout gh-pages [here](https://achint08.github.io/loklak_search/).
Also I added condition for location and website since not every user provide location and website So I have added condition to avoid errors and search service crash due to undefined variable. 
Solves #254

Fixes #254 :- New search error

---

package.json
src/app/feed/feed.module.ts
src/app/feed/info-box/info-box.component.html
src/app/feed/info-box/info-box.component.ts
src/index.html

**Fixes #260 : Added Tweets Frequency Widget in Sidebar**
The Sidebar now shows the frequency of the tweets in the query.
**Screenshot 1**
**Screenshot 2**
Demo Link: **http://rishiraj.co/loklak_search** 
**Closes #260 & #188**
@mariobehling Please review :)

Fixes #260 Tweets Frequency Widget in Sidebar

---

src/app/services/search.service.ts

**Fixes #267:**
* Fetching all results insted of only cached enteries.

FIxes #267: Fetch all instead of cached

---

.github/PULL_REQUEST_TEMPLATE.md

- Pull request template contained both the closes and the fixes line. This PR removes the fixes line as both are not needed.

Remove fixes line from PR template as closes line already present

---

src/app/home/home.component.scss

- Add background color to input field to override browser theme
**Link to live demo (if appropriate): https://uttu357.github.io/loklak_search/** 
**Closes #273**
@mariobehling Please review.. :)

fix(input-color): Add background color to override browser styles

---

src/app/feed/feed-header/feed-header.component.scss
src/app/home/home.component.scss

- Fix no scroll bug on small screens
**Link to live demo (if appropriate):https://uttu357.github.io/loklak_search/** 
**Closes #263**
@mariobehling Please review! :)

fix(home-scroll): Fix CSS for homepage

---

README.md

- Update setup instructions
**Closes #291**

Fix #291: Update setup instructions

---

src/app/feed/feed.component.html
src/app/reducers/api-user-response.ts

-  Loading icon displayed instead of showing :No results found" as experienced sometimes.
**Closes #276 **

Fixes #276 : Correct on time Display of Loading icon during search event

---

package.json
src/app/about/about.module.ts
src/app/contact/contact.module.ts
src/app/effects/api-search.effects.ts
src/app/feed/feed-footer/feed-footer.component.ts
src/app/feed/feed-header/feed-header.component.scss
src/app/feed/feed-header/feed-header.component.ts
src/app/feed/feed-not-found/feed-not-found.component.ts
src/app/feed/feed.module.ts
src/app/feed/info-box/info-box.component.ts
src/app/footer/footer.module.ts
src/app/home/home.module.ts
src/app/imprint/imprint.module.ts
src/app/models/index.ts
src/app/navbar/navbar.module.ts
src/app/pagenotfound/pagenotfound.module.ts
src/app/shared/in-viewport.directive.ts
src/app/terms/terms.module.ts
src/main.ts
src/styles/main.scss

* Angular Material2 include
* Set Theming
* Some minor indentation changes
* CLI version bumped to RC2 from RC0
**Closes #288**

Fixes #288: Include Material Module

---

src/app/feed/feed-card/feed-card.component.html

- Some misspelled function calling caused the issue. Now corrected.
-
-
**Closes #301 **

Fixes #301 : Favorite count now working

---

src/app/feed/info-box/info-box.component.html
src/app/feed/info-box/info-box.component.scss

- Add links box to sidebar
**Screenshots (if appropriate)**  
**Link to live demo (if appropriate):https://uttu357.github.io/loklak_search/search?query=fossasia** 
**Closes #309**

feat(sidebar): Add links to sidebar

---

src/app/home/home.component.html
src/app/home/home.component.scss
src/app/home/home.component.spec.ts

- Remove tagline of the start page into an alt tag of the loklak page
- Fix additional search info style
**Screenshots (if appropriate)**
**Link to live demo (if appropriate):https://uttu357.github.io/loklak_search/** 
@mariobehling Please review.. :)
**Closes #312, closes #310**

Fix #312, #310 : Design changes on homepage

---

src/app/actions/api.ts
src/app/effects/api-search.effects.ts
src/app/feed/feed-card/feed-card.component.html
src/app/feed/feed-card/feed-card.component.scss
src/app/feed/feed-card/feed-card.component.ts
src/app/feed/feed-header/feed-header.component.html
src/app/feed/feed-header/feed-header.component.scss
src/app/feed/feed-header/feed-header.component.ts
src/app/feed/feed.component.html
src/app/feed/feed.component.spec.ts
src/app/feed/feed.component.ts

- Tabs  :- Tabs are used to switch from one media type sub page to other. I have used angular material for tabs. Every tabs gives out a value corresponding to which request is sent . For example, for tab with image, request is sent with query "query /image" and same for videos.
- Images :- Images with source as `"https://pbs.twimg.com/media/{{hashcode}}.jpg"` are only displayed because images on twitter have links just like this. All other images are not removed with source link as `http://pic.twitter.com/` because they are not images links.(need to be corrected from server side)  Currently, Images are displayed in a table format for multi photos depending on number of photos linked to tweets. Dimensions of images from server is large so it is …

Partially Fixes #3 : Added image and video subpage

---

src/app/feed/feed.component.html
src/app/feed/feed.component.scss

- Shows Search message when searching.
-
-
**Link to live demo (if appropriate):** https://achint08.github.io/loklak_search/
**Closes #330 **

Fixes #330 :Shows Searching message

---

src/app/feed/feed-not-found/feed-not-found.component.html

Fixed as stated in the issue. #331

Fix #331 : Enhance "no result" page

---

src/app/terms/terms.component.html

#329
Removed link as suggested in the issue.

Fix #329 : Terms page includes unwanted links 

---

src/app/pagenotfound/pagenotfound.component.html
src/app/pagenotfound/pagenotfound.component.scss

[Demo link](https://achint08.github.io/loklak_search/xyz)

Fixes #347: Corrected Logo Text

---

src/app/services/search.service.ts
src/app/services/user.service.ts

- Added time zone offset and limit field to the request
- Space needs to be replaced by '+' in query field for request
- If  there is  '#' in the query field , query pattern needs to be like :- `%23fossasia#fossasia` for more results. Added this.
- Added timezoneOffset and limit field to the request.
- Added field to get minified reponse for `user.json` request.
**Link to live demo (if appropriate):** https://achint08.github.io/loklak_search/

Corrected query pattern for requests & Added time zone offset and limit field to the request

---

src/app/feed/feed-header/feed-header.component.html
src/app/feed/feed-header/feed-header.component.scss
src/app/feed/feed-header/feed-header.component.ts
src/app/feed/feed.component.html
src/app/feed/feed.component.spec.ts
src/app/feed/feed.component.ts
src/app/feed/feed.module.ts
src/styles/main.scss
src/styles/partials/_material-generic.scss

* This uses MdAutocomplete for the suggestion box
* Reduces the duplicate code
[Breaking Changes]
* The implementaion of the Tabs aand filtering is removed.
* It will be further be improved in the next PR as before filtering we need to have the Query structure ready to make it possible to have the best use of it
**Closes #362**

Fixes #362: MdAutocomplete for suggestion box

---

src/app/effects/api-usersearch.effects.ts
src/app/services/search.service.ts
src/app/services/user.service.ts

Improves speed of user info box and corrects result for `from:User` search pattern. Corrected query pattern for search service ( #358)  . Made follow count customizable (#359) :- 
- For user info-box , follow count required is 10, and
-  For followers page, follow count required is 1000.
**Closes #**

Fixes #358 #359 :- Corrected query pattern for search service . Made follow count customizable.

---

src/app/services/search.service.spec.ts
src/app/services/suggest.service.spec.ts
src/app/services/user.service.spec.ts
src/app/shared/mocks/feedItem.mock.ts

- Added tests ( #372) for :-
1. Search Service
2. User Service
3. Suggest Service
- Added mock for Api response which is needed in these tests to check if the services are receiving the response from some mock backend. Moreover, will be needing this mock response later to testing other components.
- We are checking if the services are called and request is sent to the correct API URL address.
@daminisatya @hemantjadon @vibhcool @singhpratyush @djmgit Please review. :)

Partially fixes #372: Added tests for Services

---

src/app/feed/feed.component.scss
src/app/footer/footer.component.scss
src/app/home/home.component.html
src/app/home/home.component.scss
src/app/home/home.component.ts
src/app/home/home.module.ts

FIxes the following Inconsistencies
**Closes #370**

Fixes #370 : Home Page UI Inconsistency remove

---

src/app/about/about.module.ts
src/app/app.module.ts
src/app/contact/contact.module.ts
src/app/feed/feed.module.ts
src/app/imprint/imprint.module.ts
src/app/navbar/navbar.module.ts
src/app/pagenotfound/pagenotfound.module.ts
src/app/terms/terms.module.ts

* Remove unnecessary imports from the all the modules
**Closes #378**

Fixes #378: Remove unnecessary module imports

---

src/app/actions/api.ts
src/app/models/api-user-response.ts
src/app/reducers/api-response.spec.ts
src/app/reducers/api-response.ts
src/app/reducers/api-user-response.spec.ts
src/app/reducers/api-user-response.ts
src/app/services/user.service.ts
src/app/shared/mocks/feedItem.mock.ts
src/app/shared/mocks/suggestResponse.mock.ts
src/app/shared/mocks/userResponse.mock.ts

-Added tests for api-response and user-response reducers ( Didn't add tests for all other reducers to avoid big PR)
-added mocks
- configured user model
@hemantjadon  @vibhcool @djmgit Please review :)

Added tests for api-response and user-response reducers

---

src/app/feed/feed.component.html
src/app/feed/feed.component.ts
src/app/models/api-user-response.ts
src/app/reducers/pagination.spec.ts
src/app/reducers/pagination.ts
src/app/reducers/search.spec.ts
src/app/reducers/search.ts
src/app/reducers/suggest-response.spec.ts
src/app/reducers/suggest-response.ts
src/app/reducers/suggest.spec.ts
src/app/reducers/suggest.ts
src/app/shared/mocks/userResponse.mock.ts

- Added tests for search, pagiantion, suggest , suggest-response reducers
- Made access specifiers of some properties of feed component public.
- Correct user response model.

Added tests for reducers. Made changes to user response model.

---

src/app/effects/api-search.effects.spec.ts
src/app/effects/api-suggest.effects.spec.ts
src/app/effects/api-suggest.effects.ts
src/app/effects/api-usersearch.effects.spec.ts
src/app/effects/api-usersearch.effects.ts
src/app/effects/pagination.effects.spec.ts

-Added tests for
* Search Effects
* Pagination Effects
* User Effects
* Suggest Effects

Added tests for effects

---

src/app/about/about.component.spec.ts
src/app/about/about.component.ts
src/app/contact/contact.component.spec.ts
src/app/contact/contact.component.ts
src/app/feed/feed.component.ts
src/app/home/home.component.spec.ts
src/app/home/home.component.ts
src/app/reducers/api-user-response.ts
src/app/terms/terms.component.spec.ts
src/app/terms/terms.component.ts

- Added titles for pages
Demo Link :- https://achint08.github.io/loklak_search/
Please review @hemantjadon .

Fixes #391 :- Added titles

---

src/app/app.component.spec.ts
src/app/contact/contact-form/contact-form.component.scss
src/app/contact/contact-form/contact-form.component.spec.ts
src/app/contact/contact-form/contact-form.component.ts
src/app/contact/contact.component.html
src/app/utils/array.spec.ts
src/app/utils/type.spec.ts
src/app/utils/type.ts

- Added tests for app component
- Added tests for contact form component
- Added tests for utils
- Some minor bug fixes
Please review @hemantjadon

Added tests for contact form and app compoment and utils

---

src/app/feed/feed-card/feed-card.component.html
src/app/feed/feed-card/feed-card.component.ts

Images and video urls which were removed during the restructuring of application are implemented back.
**Link to live demo (if appropriate):https://hemantjadon.github.io/loklak_search** 
**Closes #407**

Images and videos in Feed Cards

---

src/app/actions/media-wall.ts
src/app/app.module.ts
src/app/effects/media-wall-search.effects.ts
src/app/feed/feed-header/feed-header.component.html
src/app/feed/feed-header/feed-header.component.scss
src/app/feed/feed-header/feed-header.component.ts
src/app/feed/feed.component.html
src/app/feed/feed.component.spec.ts
src/app/media-wall/media-wall-card/media-wall-card.component.html
src/app/media-wall/media-wall-card/media-wall-card.component.scss
src/app/media-wall/media-wall-card/media-wall-card.component.spec.ts
src/app/media-wall/media-wall-card/media-wall-card.component.ts
src/app/media-wall/media-wall-linker/media-wall-linker.component.html
src/app/media-wall/media-wall-linker/media-wall-linker.component.scss
src/app/media-wall/media-wall-linker/media-wall-linker.component.spec.ts
src/app/media-wall/media-wall-linker/media-wall-linker.component.ts
src/app/media-wall/media-wall-routing.module.ts
src/app/media-wall/media-wall.component.html
src/app/media-wall/media-wall.component.scss
src/app/media-wall/media-wall.component.spec.ts
src/app/media-wall/media-wall.component.ts
src/app/media-wall/media-wall.module.ts
src/app/reducers/index.ts
src/app/reducers/media-wall.spec.ts
src/app/reducers/media-wall.ts

- Added basic prototype of media wall
- Masonry view
- Added option to get different view  as a media wall
**TODO**
- Integrating media wall component with the search result (in the next PR).
Media Wall View
**Closes #386 , #398 **
Please review @mariobehling @hemantjadon @rishiraj824  @vibhcool @singhpratyush @djmgit @kavithaenair

Fixes #396 #398:- Prototype of loklak media wall

---

src/app/feed/feed-card/feed-card.component.html
src/app/feed/feed-card/feed-card.component.scss
src/app/feed/feed-header/feed-header.component.ts
src/app/feed/feed.component.scss
src/app/media-wall/media-wall-card/media-wall-card.component.html
src/app/media-wall/media-wall-card/media-wall-card.component.scss
src/app/media-wall/media-wall-header/media-wall-header.component.html
src/app/media-wall/media-wall-header/media-wall-header.component.scss
src/app/media-wall/media-wall-header/media-wall-header.component.spec.ts
src/app/media-wall/media-wall-header/media-wall-header.component.ts
src/app/media-wall/media-wall.component.html
src/app/media-wall/media-wall.component.scss
src/app/media-wall/media-wall.component.spec.ts
src/app/media-wall/media-wall.component.ts
src/app/media-wall/media-wall.module.ts

- Added Hover effects and actions to media wall cards
- Added header to media wall
- Made media wall card more responsive.
- Some minor changes to feed card.
**Closes #420 #421**
Please review @hemantjadon @djmgit @kavithaenair @vibhcool @singhpratyush @rishiraj824 .

Fixes #420 #421 :- Improves Media Wall

---

src/app/home/home.component.html
src/app/home/home.component.scss
src/app/home/home.component.spec.ts
src/app/home/home.component.ts

Fixes #313:-
-  showing top hashtags on the home page
**Link to live demo:**
**Screenshots**
@hemantjadon @kavithaenair @vibhcool @rishiraj824  Please review. :)

 Fixes #313 :- Hashtags on home page

---

src/app/feed/feed-card/feed-card.component.html
src/app/feed/feed-card/feed-card.component.scss
src/app/media-wall/media-wall-card/media-wall-card.component.html
src/app/media-wall/media-wall-card/media-wall-card.component.scss
src/app/media-wall/media-wall-header/media-wall-header.component.scss
src/app/media-wall/media-wall-linker/media-wall-linker.component.html
src/app/media-wall/media-wall-linker/media-wall-linker.component.scss
src/app/media-wall/media-wall-linker/media-wall-linker.component.ts
src/app/media-wall/media-wall.component.scss

- Implemented a new design for media wall cards.
- Defined columns for all type of screen-sizes
- Changed background color
**Screenshots** 
**Link to live demo:** 
**Closes #427 **
Please review @mariobehling @hemantjadon @vibhcool @singhpratyush @djmgit @kavithaenair

Fixes #427 :- Improves media wall cards design

---

package.json
src/app/effects/query.effects.ts
src/app/models/filters.ts
src/app/models/query.spec.ts
src/app/models/query.ts
src/app/reducers/media-wall.ts
src/app/reducers/query.ts
src/app/reducers/search.ts
src/app/shared/mocks/feedItem.mock.ts
src/app/utils/array.spec.ts
src/app/utils/array.ts
src/app/utils/index.ts
src/app/utils/reg-exp.ts
src/app/utils/string-validators.spec.ts
src/app/utils/string-validators.ts

* The functions to properly convert the query string to the query object
* Also includes unit tests for these functions
**Closes #432**

Fixes#432: Reverse process string to query object

---

src/app/feed/feed-header/feed-header.component.scss
src/app/feed/feed.component.scss
src/app/home/home.component.scss
src/styles/main.scss
src/styles/partials/_mixins.scss
src/styles/partials/_variables.scss

* Matching the theme color of the application to the loklak theme
* Initiates the theme usage in the application
* This can be taken forward in subsequent PR's
https://hemantjadon.github.io/loklak_search/
**Closes #441 **

Fixes#441: Uniform theming for application colors

---

src/app/actions/api.ts
src/app/actions/trends.ts
src/app/app.module.ts
src/app/effects/api-search.effects.ts
src/app/home/home.component.html
src/app/home/home.component.scss
src/app/home/home.component.spec.ts
src/app/home/home.component.ts
src/app/home/home.module.ts
src/app/models/api-response.ts
src/app/reducers/api-trends-response.ts
src/app/reducers/index.ts
src/app/reducers/trends.ts

* Include new Redux state to store the trending hashtags
* Show the trening icon on the home page along with tooltip
**Closes #440 **

Improve top hashtags displayed on home page

---

src/app/actions/media-wall-custom.ts
src/app/models/index.ts
src/app/models/media-wall-custom.ts
src/app/reducers/index.ts
src/app/reducers/media-wall-custom.spec.ts
src/app/reducers/media-wall-custom.ts

- Adds ngrx structure for media wall customization
- Customization for -
1.  Wall Header
2. Wall Background
3. Wall Cards
**Closes #449 **

Fixes #449: Adds ngrx structure for media wall customization

---

src/app/feed/feed-advanced-search/feed-advanced-search.component.ts
src/app/feed/feed-header/feed-header.component.html
src/app/feed/feed-header/feed-header.component.ts
src/app/feed/feed.component.html
src/app/feed/feed.component.spec.ts
src/app/feed/feed.component.ts

Closing suggest box after the the query is fetched.
* This makes sure that suggestion panel is closed after the results are fetched
**Closes #439 **

Close suggest box after fetching query

---

src/app/effects/api-search.effects.ts
src/app/feed/feed.component.ts
src/app/pagenotfound/pagenotfound.component.ts

* Using title service for changing titles dynamically on every search
**Closes #456**

Set titles dynamically on each query

---

src/index.html

* Adding`meta` tags for SEO
* Please suggest some other keywords which can be added.
**Closes #455**

Meta tags for SEO

---

package.json
src/app/media-wall/media-wall-header/media-wall-header.component.html
src/app/media-wall/media-wall-header/media-wall-header.component.scss
src/app/media-wall/media-wall-header/media-wall-header.component.ts
src/app/media-wall/media-wall.component.html
src/app/media-wall/media-wall.component.scss
src/app/media-wall/media-wall.component.spec.ts
src/app/media-wall/media-wall.component.ts
src/app/media-wall/media-wall.module.ts
src/app/shared/full-screen.directive.ts
src/app/shared/index.ts

- Adds Fullscreen option
- Adds dialog box for customization menu implemetation.
**Closes #435  **
**Note**
Gh-pages show the basic prototype of customization menu, however, the option will be disabled in the deployment until some stable version of setting is made.

Fixes #435 :- Full screen mode

---

src/index.html

Adds meta data for social media cards
**Closes #467 **

Social media metadata for preseentation

---

src/app/media-wall/media-wall-card/media-wall-card.component.html
src/app/media-wall/media-wall-card/media-wall-card.component.scss
src/app/media-wall/media-wall-card/media-wall-card.component.spec.ts
src/app/media-wall/media-wall-card/media-wall-card.component.ts
src/app/media-wall/media-wall-header/media-wall-header.component.html
src/app/media-wall/media-wall-header/media-wall-header.component.scss
src/app/media-wall/media-wall-header/media-wall-header.component.ts
src/app/media-wall/media-wall-linker/media-wall-linker.component.html
src/app/media-wall/media-wall-linker/media-wall-linker.component.ts
src/app/media-wall/media-wall.component.html
src/app/media-wall/media-wall.component.scss
src/app/media-wall/media-wall.component.spec.ts
src/app/media-wall/media-wall.component.ts

- Link media wall properties to ngrx state properties
**Closes #459  **

Fixes #459: Linking media wall properties to ngrx state properties

---

.angular-cli.json
package.json
src/app/feed/feed-advanced-search/feed-advanced-search.component.html
src/app/feed/feed-advanced-search/feed-advanced-search.component.scss
src/app/feed/feed-advanced-search/feed-advanced-search.component.ts
src/app/feed/feed-header/feed-header.component.html
src/app/feed/feed-header/feed-header.component.scss
src/app/feed/feed-header/feed-header.component.ts
src/app/home/home.component.html
src/app/home/home.component.scss

* Improve UI of feed header component
* Make The feed header A11y compatible
* Add Advanced search features to the results
* Add location based search
* Add time restricted search
**Closes #438, #43**

Feed header UI enhancement and adv search

---

src/app/actions/query.ts
src/app/effects/api-search.effects.ts
src/app/effects/query.effects.ts
src/app/feed/feed.component.ts
src/app/pagenotfound/pagenotfound.component.spec.ts

* Update the URL according to the query fetched. 
* This allows the easy shareability of query URL's in their complete form including filters and other customizations
**Closes #462**

Correcting the relocation according to query

---

package.json
src/app/feed/feed-card/feed-card.component.html
src/app/feed/feed-card/feed-card.component.scss
src/app/feed/feed-card/feed-card.component.spec.ts
src/app/feed/feed.module.ts
src/app/home/home.component.html
src/app/home/home.component.spec.ts
src/app/home/home.module.ts
src/app/lazy-img/lazy-img.component.html
src/app/lazy-img/lazy-img.component.scss
src/app/lazy-img/lazy-img.component.spec.ts
src/app/lazy-img/lazy-img.component.ts
src/app/lazy-img/lazy-img.module.ts
src/app/lazy-img/lazy-img.service.spec.ts
src/app/lazy-img/lazy-img.service.ts
src/polyfills.ts
src/styles/main.scss

* Lazy loading image depending on the position of the element wrt to viewport
* Using Intersection obsever to detect
* Using fetchAPI to asynchronoulsy fetch the Binary data stream and convert it into image
* Add semantic loading information
* Along with the error messages specially 404 errors for images of varied sizes.
**Closes #471**
**In reference to #433**

Lazy loading of images

---

src/app/actions/api.ts
src/app/actions/media-wall-custom.ts
src/app/actions/media-wall-pagination.ts
src/app/actions/media-wall-query.ts
src/app/actions/media-wall.ts
src/app/app.module.ts
src/app/effects/api-search.effects.ts
src/app/effects/media-wall-pagination.effects.ts
src/app/effects/media-wall-search.effects.ts
src/app/media-wall/media-wall-header/media-wall-header.component.scss
src/app/media-wall/media-wall-linker/media-wall-linker.component.html
src/app/media-wall/media-wall.component.html
src/app/media-wall/media-wall.component.scss
src/app/media-wall/media-wall.component.ts
src/app/reducers/api-media-wall-response.ts
src/app/reducers/index.ts
src/app/reducers/media-wall-pagination.ts
src/app/reducers/media-wall-query.spec.ts
src/app/reducers/media-wall-query.ts
src/app/reducers/media-wall-search.ts

- Auto refreshing mode for media wall
- Adds Animation for adding new feeds on media wall
- Triggers new request after every 5 seconds
- Separates actions, reducers for media wall.
**Closes #460**

Fixes #460: Auto refreshing mode for media walls

---

src/app/lazy-img/lazy-img.service.ts

Removing the promise nesting from the Lazy img service 
**Closes #479**
**Followup of #470**

Remove promise nesting

---

src/app/actions/media-wall-query.ts
src/app/effects/api-search.effects.ts
src/app/effects/media-wall-search.effects.ts
src/app/media-wall/media-wall.component.html
src/app/media-wall/media-wall.component.ts
src/app/reducers/media-wall-query.spec.ts
src/app/reducers/media-wall-query.ts

- Adds Title Service for media walls
- For tweet from some particular user, the displayString will be '@user' and not `from: user`
**Closes #477 **

Fixes #477: Title Service for media walls

---

package.json

-  Updated correct version of enhanced-resolve
Reference: https://github.com/webpack/enhanced-resolve/issues/98 , https://github.com/angular/angular-cli/issues/7113
**Closes #485 **

Fixes #485: Updated correct version of enhanced-resolve

---

src/app/home/home.component.ts
src/testing/router-stubs.ts

* Sending the query param during relocation from home to feed
**Closes #483**

Navigate correction from home to feed

---

src/app/home/home.component.html
src/app/lazy-img/lazy-img.component.html
src/app/lazy-img/lazy-img.component.ts

* Adding title attribute the element, so that browsers render it correctly as the tooltip on hover
**Closes #455**

Add title attribute to LazyImgComponent

---

src/app/home/home.component.html
src/app/home/home.component.scss

Top hashtags in 2 lines (5 in one and 4 in one)
**Closes #495**

Top hashtags in 2 lines

---

src/app/feed/feed-advanced-search/feed-advanced-search.component.html
src/app/feed/feed-advanced-search/feed-advanced-search.component.scss
src/app/feed/feed-advanced-search/feed-advanced-search.component.ts
src/app/feed/feed-header/feed-header.component.html
src/app/feed/feed-header/feed-header.component.scss

- Restore view button on header
http://achint08.github.io/loklak_search/
**Closes #489 **

 Fixes #489: Restore view button on header

---

src/app/media-wall/media-wall-not-found/media-wall-not-found.component.html
src/app/media-wall/media-wall-not-found/media-wall-not-found.component.scss
src/app/media-wall/media-wall-not-found/media-wall-not-found.component.spec.ts
src/app/media-wall/media-wall-not-found/media-wall-not-found.component.ts
src/app/media-wall/media-wall.component.html
src/app/media-wall/media-wall.component.spec.ts
src/app/media-wall/media-wall.module.ts

- Add no results page to media wall
**Closes #482**

Fixes #482: Add no results page to media wall

---

src/app/feed/feed-advanced-search/feed-advanced-search.component.scss

Reduces the button size to match the UI scheme of the application
**Closes #506**

Reduce header button size

---

src/app/media-wall/media-wall-card/media-wall-card.component.html
src/app/media-wall/media-wall-card/media-wall-card.component.scss
src/app/media-wall/media-wall-card/media-wall-card.component.spec.ts
src/app/media-wall/media-wall.component.html
src/app/media-wall/media-wall.module.ts

-  Adding lazy loading image in media wall
**Test Link**
**Closes #501 **

Fixes #501: Adding lazy loading image in media wall

---

src/app/feed/feed-not-found/feed-not-found.component.html

Link to the loklak issue tracker added to the "No results found page"
**Closes #308**

Add link for issue tracker for no results

---

src/app/home/home.component.spec.ts
src/app/home/home.component.ts

Change title of home page

---

src/app/home/home.component.spec.ts

- Improved Test for new Title and alt text
@mariobehling @hemantjadon Please see this.

Test for new Title and alt text

---

404.html

* Migrates to loklak.org, redirective refresh 
**Closes #519**

Migrating to loklak.org from loklak.net

---

README.md
README.rst
src/index.html

- Instance of loklak.net are changed to loklak.org
**Closes #523**

Replace instances of loklak.net with loklak.org

---

package.json
src/app/media-wall/media-wall.module.ts

- Media wall working again
**Closes #525**

Fixes #525: Media Wall working again

---

src/app/app-masonry/app-masonry.component.ts
src/app/app-masonry/app-masonry.module.ts
src/app/app-masonry/brick.ts
src/app/app-masonry/index.ts
src/app/app-masonry/masonry-options.ts
src/app/effects/api-search.effects.ts
src/app/effects/media-wall-pagination.effects.ts
src/app/media-wall/media-wall.component.html
src/app/media-wall/media-wall.component.scss
src/app/media-wall/media-wall.component.spec.ts
src/app/media-wall/media-wall.component.ts
src/app/media-wall/media-wall.module.ts
src/app/reducers/api-media-wall-response.ts
src/app/reducers/media-wall-query.ts
src/app/utils/index.ts
src/app/utils/remove-duplicate.ts

- Pagination using `source=twitter`
- Auto-refresh in 10 seconds to avoid too many feeds
Scroll to bottom to get more feeds. Also wait for 30 seconds for auto-refresh.
https://achint08.github.io/loklak_search/wall?query=fossasia
**Closes #510**

Fixes #510: Improve infinite pagination in media wall

---

package.json

- Added masonry-layout dependency
Please add @mariobehling @hemantjadon .

Added masonry-layout dependency

---

src/app/about/about.component.html

About page footer now correctly rendering
**Closes #529**

About page footer fixup

---

src/app/feed/feed-linker/feed-linker.component.scss

- Change cursor type from default to text
**Closes #537 **
**Text Link**

Fixes #537: Change cursor type from default to text

---

.angular-cli.json
package.json

Basic service worker for the precaching of the application static assets.
https://hemantjadon.github.io/loklak_search/
**Closes #512**

Basic Service worker for precaching the static resources

---

src/app/actions/media-wall-direct-url.ts
src/app/app.module.ts
src/app/effects/api-search.effects.ts
src/app/effects/index.ts
src/app/effects/media-wall-direct-url.effects.ts
src/app/effects/media-wall-pagination.effects.ts
src/app/media-wall/media-wall-direct-url/media-wall-direct-url.component.html
src/app/media-wall/media-wall-direct-url/media-wall-direct-url.component.scss
src/app/media-wall/media-wall-direct-url/media-wall-direct-url.component.spec.ts
src/app/media-wall/media-wall-direct-url/media-wall-direct-url.component.ts
src/app/media-wall/media-wall-menu/media-wall-menu.component.html
src/app/media-wall/media-wall-menu/media-wall-menu.component.ts
src/app/media-wall/media-wall-query/media-wall-query.component.ts
src/app/media-wall/media-wall.component.html
src/app/media-wall/media-wall.component.spec.ts
src/app/media-wall/media-wall.component.ts
src/app/media-wall/media-wall.module.ts
src/app/models/index.ts
src/app/models/media-wall-direct-url.ts
src/app/reducers/api-media-wall-response.ts
src/app/reducers/index.ts
src/app/reducers/media-wall-design.ts
src/app/reducers/media-wall-direct-url.ts
src/app/reducers/media-wall-query.spec.ts
src/app/reducers/media-wall-query.ts

- Direct URL for media wall
https://achint08.github.io/loklak_search/wall?query=%23trump
**Closes #521**

Fixes #521: Direct URL for media wall

---

src/app/media-wall/media-wall.component.html
src/app/media-wall/media-wall.component.scss

- Shows sidebar only when cursor is active
-
-
achint08.github.io/loklak_search
**Closes #551 **

Fixes #551: Shows sidebar only when cursor is active

---

src/app/feed/info-box/info-box.component.html
src/app/feed/info-box/info-box.component.scss

- Adds links to the sidebar 
**Closes #559**

Fixes #559: adds links to the sidebar

---

README.md

- Mailing List Group Updated
**Closes #542**

Google Group Link Updated in README.md

---

src/app/feed/feed-card/feed-card.component.ts

Little code cleanup Fixes #572

[CodeCleanup] Clean invalid image urls

---

src/app/home/home.component.scss

Fixes #563 Bottom bar is fixed to bottom

---

src/app/services/search.service.spec.ts
src/app/services/suggest.service.spec.ts
src/app/services/user.service.spec.ts

- Now loklak_search make queries from https://api.loklak.org
**Closes #589

Fixes #589 Make queries from https

---

package-lock.json
package.json
src/app/feed/feed-advanced-search/feed-advanced-search.component.spec.ts
src/app/feed/feed-header/feed-header.component.spec.ts
src/app/feed/feed.component.spec.ts
src/app/media-wall/media-wall-custom-background/media-wall-custom-background.component.spec.ts
src/app/media-wall/media-wall-custom-card/media-wall-custom-card.component.spec.ts
src/app/media-wall/media-wall-custom-header/media-wall-custom-header.component.spec.ts
src/app/media-wall/media-wall-customization/media-wall-customization.component.spec.ts
src/app/media-wall/media-wall-design/media-wall-design.component.spec.ts
src/app/media-wall/media-wall-menu/media-wall-menu.component.spec.ts
src/app/media-wall/media-wall-moderation/media-wall-moderation.component.spec.ts
src/app/media-wall/media-wall-not-found/media-wall-not-found.component.spec.ts
src/app/media-wall/media-wall-query/media-wall-query.component.spec.ts
src/app/media-wall/media-wall.component.spec.ts

- Version evening with angular material beta.11
- Removes material module from all locations
**Closes #577**

Angular material version bump

---

src/app/feed/info-box/info-box.component.html

I have done a minor UI enhancement 
Previous one:
After Changes:

Fixes #574 Changes formatting of side card in search

---

src/app/feed/info-box/info-box.component.html

Reverts fossasia/loklak_search#575

Revert "Fixes #574 Changes formatting of side card in search"

---

src/app/feed/feed-advanced-search/feed-advanced-search.component.html

- Updates dropdown list removing the repeated 'Country:'
**Closes #598 **

Fixes Issue #598: 'Country:' repeated in dropdown 

---

.github/ISSUE_TEMPLATE.md

- Adds Issue template to understand the issue better.
**Closes #605 **

Fixes#605 Adds Issue Template

---

README.md

- Grammatical Errors
**Closes #**

Update README.md (#596)

---

src/app/feed/feed-header/feed-header.component.html
src/app/feed/feed-header/feed-header.component.scss
src/app/feed/feed-header/feed-header.component.ts
src/app/home/home.component.scss

- Add close suggestion box on pressing return key functionality
- Update UI of search input box (Background made fully white)
- [ Pending ] Match width of suggestion box to search box
https://ajayns.github.io/loklak_search/
**Closes #601**

Addresses #601 Improvements in the UI of suggestion box.

---

src/app/feed/feed-advanced-search/feed-advanced-search.component.html
src/app/feed/feed-advanced-search/feed-advanced-search.component.scss

Addresses #547 
- Implementation of layout same as Google
[gh pages deployment](https://ParthS007.github.io/loklak_search)

 Fixes#547 Different font sizes and styles in same area

---

.travis.yml
README.md
pr_deploy.sh

Fixes #610 
- Adds auto deploy to every pull request on surge.
- Now future PRs will be deployed automatically.
**Deployment Link: [https://pr-621-fossasia-loklaksearch.surge.sh/](https://pr-621-fossasia-loklaksearch.surge.sh/) ** 
**Closes #610 **

Fixes#610 Auto deployment using Surge

---

src/styles/partials/_material-generic.scss

- Completely Fixed UI of suggestion box
**Link to live demo (if appropriate):** https://pr-626-fossasia-loklaksearch.surge.sh/
**Closes #625 **

Fixes#625 Improvements in UI of suggestion box

---

src/app/feed/info-box/info-box.component.html
src/app/feed/info-box/info-box.component.scss

- Updated UI for infobox
Before
After
**Closes #628**

Addresses #629 Updated UI for infobox

---

src/app/feed/info-box/info-box.component.html
src/app/feed/info-box/info-box.component.scss

Reverts fossasia/loklak_search#629

Revert "Addresses #629 Updated UI for infobox"

---

README.md

- **_Added a dependency named `webpack`_** :tada: 
- **_Added this fix to `loklak_search` documentation_** :+1:

Fixes #636 : Added node `webpack` dep. to README.md

---

.gitignore
README.md
src/app/about/about.component.html
src/app/feed/feed-card/feed-card.component.ts
src/app/feed/info-box/info-box.component.html
src/app/footer/footer.component.html
src/app/service-box/service-box.component.html
src/app/shared/mocks/feedItem.mock.ts
src/app/shared/mocks/userResponse.mock.ts
src/index.html

- Migrating from 'http' to 'https'
**Closes #**
Closes #634

Fixes #634: Migrate: http->https

---

.github/PULL_REQUEST_TEMPLATE.md

Adds surge based url as each pr is deployed to it via Travis.
**Closes #630 **

Updates Pull Request template to contain live surge link

---

package.json

- Fixes Travis Build
- Added enhance resolve
**Link to live demo**: http://pr-642-fossasia-loklaksearch.surge.sh 
**Closes #641 **

Fixes#641 Fixes Travis Build

---

.angular-cli.json
src/index.html
src/manifest.json

-  The App provide fallback content when Javascript is not available.
-  Adding manifest.
**Link to live demo: http://pr-643-fossasia-loklaksearch.surge.sh** 
Fixes partially #639 
@mariobehling @harshit98 @singhpratyush @hemantjadon   . Please review

Addresses#639 Increase PWA audit

---

src/app/service-box/service-box.component.html
src/app/service-box/service-box.component.scss

- Made changes in service-box component to close navigation menu on top right side when clicked outside
**Link to live demo: ** http://pr-652-fossasia-loklaksearch.surge.sh
**Closes #632 #638**

Fixed #632: '9-dot navigation menu to other apps not closing'

---

src/app/feed/feed-header/feed-header.component.scss

-Improved UI for smaller screen sizes.
**Surge Link:**
http://deeply-earthquake.surge.sh/
**Screenshots:** 
**Fixes**#646
**Screenshots:** 
**Fixes**#646

Fixes#646:Improved UI for smaller screen sizes.

---

README.md

Signed-off-by: Yash Ladha <yashladhapankajladha123@gmail.com>
- Corrected Node version details in README
-
-
**Closes #654**

Fixes #654: Corrected Node version in Readme

---

.bowerrc
.gitignore
README.md

- Removed bower and its components from project. This is the first half of migration from bower to yarn.
**Link to live demo: http://pr-662-fossasia-loklaksearch.surge.sh** 
**Closes #658**
@singhpratyush please preview. Thanks.

Remove bower

---

.travis.yml
Dockerfile

- Add `Dockerfile` for the project to create an optimized build with `nginx` server
- Add command to build Docker image with Travis
**Link to live demo:** http://165.227.107.53/
Docker build log - 
```
Sending build context to Docker daemon  34.33MB
Step 1/11 : FROM node:6.9.1-alpine as builder
---> 3c6fe43f14ca
Step 2/11 : COPY package.json package-lock.json ./
---> 66ce81c3e011
Step 3/11 : RUN npm set progress=false && npm config set depth 0 && npm cache clean --force
---> Running in 375847755bd5
npm info it worked if it ends with ok
npm info using npm@3.10.8
npm info using node@v6.9.1
npm info config set "progress" "false"
npm info ok 
npm info it worked if it ends with ok
npm info using npm@3.10.8
npm info using node@v6.9.1
npm info config set …
```

Add Dockerfile and Travis build

---

src/app/service-box/service-box.component.html
src/app/service-box/service-box.component.scss
src/app/service-box/service-box.component.ts
tslint.json

- Fixes #671 and #632 
**Link to live demo: ** http://pr-681-fossasia-loklaksearch.surge.sh
**Closes #671 and #632 **

Fixed #671 and #632:Resolved bugs with Service Box (Links work fine and Service box closes when clicked outside of it)

---

src/app/lazy-img/lazy-img.service.ts

- Use getBoundingClientRect() and rootBounds instead of 
IntersectionObserverEntry.target. intersectionRatio to check if target element is inside root (viewport)
Fixes issue with images not showing up on the wall page and search page on mozilla firefox.
**Links to live demo:**
https://kapillamba4.github.io/loklak_search/
http://pr-677-fossasia-loklaksearch.surge.sh
**Closes #569**

Fixes #569. Use getBoundingClientRect() instead of intersectionRatio

---

src/app/home/home.component.ts

- Handle "no aggregations from backend" case
- Also fixes "first character missing" issue (#580)
Link - https://pr-686-fossasia-loklaksearch.surge.sh/
Closes #663 #580

Fix 663: Handle case when no hashtags returned by API at home

---

src/app/feed/feed-header/feed-header.component.html
src/app/lazy-img/lazy-img.service.ts
src/app/services/search.service.ts

- This PR removes the 404 bug gotten in the first request made immediately on loading the page. I believe this PR should completely fix #688 
**Screenshots** 
BEFORE
AFTER
Test link: [https://pr-692-fossasia-LoklakSearch.surge.sh](https://pr-692-fossasia-LoklakSearch.surge.sh)
**Closes #688 **

Final fix for 404 error in image

---

.gitignore

- Updated .gitignore to ignore tracking of .vscode/
**Screenshots (if appropriate)**  Not applicable
**Link to live demo: http://pr-700-fossasia-loklaksearch.surge.sh** 
**Closes #699**

Add .vscode/ to .gitignore

---

package-lock.json
package.json

- Updated version of vulnerable dependencies in codebase. 
**Screenshots (if appropriate)**  Not applicable
**Link to live demo: http://pr-707-fossasia-loklaksearch.surge.sh** 
**Closes #706**

Fixes #706: Update vulnerable dependencies in codebase

---

.travis.yml

- Corrected order of ```cache``` parameter.
**Screenshots (if appropriate)** Not applicable
**Link to live demo: http://pr-705-fossasia-loklaksearch.surge.sh** 
**Closes #704**

Fixes #704: Update travis file

---

src/app/home/home.component.html
src/app/home/home.component.scss
src/app/home/home.component.spec.ts
src/app/home/home.component.ts

- Adds trending hashtags section on Home page.
**Link to live demo: http://pr-715-fossasia-loklaksearch.surge.sh** 
**Closes #**

Parent #714: Add Trending Hashtags section on Home page

---

package-lock.json
package.json
src/app/actions/speech.ts
src/app/app.component.html
src/app/app.component.spec.ts
src/app/app.component.ts
src/app/app.module.ts
src/app/feed/feed-header/feed-header.component.html
src/app/feed/feed-header/feed-header.component.scss
src/app/feed/feed-header/feed-header.component.spec.ts
src/app/feed/feed-header/feed-header.component.ts
src/app/feed/feed.component.spec.ts
src/app/feed/feed.module.ts
src/app/home/home.component.spec.ts
src/app/home/home.component.ts
src/app/reducers/index.ts
src/app/reducers/speech.spec.ts
src/app/reducers/speech.ts
src/app/speech/speech.component.html
src/app/speech/speech.component.scss
src/app/speech/speech.component.spec.ts
src/app/speech/speech.component.ts

- Created a new component for speech recognition.
- Embedded voice search feature on results page.
**Screenshots (if appropriate)** Not applicable.
**Link to live demo: http://pr-711-fossasia-loklaksearch.surge.sh** 
**Closes #697 #698**

Design separate component for speech recognition and embed voice search on results page

---

README.md

Fixes:#709
- Added Bootstrap 3.3.2 to the technology stack in README.MD 
**Closes #**

updated the READEME.md specifying the responsive design technology

---

src/app/media-wall/media-wall-custom-background/media-wall-custom-background.component.scss
src/app/media-wall/media-wall-custom-header/media-wall-custom-header.component.scss
src/app/media-wall/media-wall-customization/media-wall-customization.component.scss
src/app/media-wall/media-wall-design/media-wall-design.component.scss
src/app/media-wall/media-wall-menu/media-wall-menu.component.scss
src/app/media-wall/media-wall-moderation/media-wall-moderation.component.scss
src/app/media-wall/media-wall-query/media-wall-query.component.scss

- Removed unwanted outlines from buttons on their click.
- Adjusted margin between the buttons. 
- Adjusted the font size.
1.
2.
**Link to live demo: http://pr-717-fossasia-loklaksearch.surge.sh** 
**Closes #**

Parent #716: Fix UI bugs in Media-Wall Component

---

src/app/services/search.service.ts
src/app/services/suggest.service.ts
src/app/services/user.service.ts

- Put again the get request to api call if there is an error in first request(Usually this is the problem in not getting results many of times).
**Link to live demo: http://pr-723-fossasia-loklaksearch.surge.sh** 
**Closes #722**

Fixes #722: Retry get request if error in first request in api call

---

src/app/home/home.component.html
src/app/home/home.component.scss

- Increased no of trending hashtags displayed on home page.
- Improve structure of display of hashtags
**Link to live demo: http://pr-725-fossasia-loklaksearch.surge.sh** 
**Closes #**

Fixes #714: Increase no of hashtags and improve hashtag display

---

package-lock.json
package.json
src/app/feed/feed.component.ts

- Updated project modules causing security vulnerabilities.
- Fixed module deprecations.
- Fixed ```--single-run``` undefined issue.
Note: Only one low level security vulnerability is left out of 35 because its not been fixed yet in official release.
After merging please run: ```npm audit``` to check for the one left vulnerability.
**Link to live demo: http://pr-736-fossasia-loklaksearch.surge.sh** 
**Closes #735**
**Also Fixes: #706**

Fixes #735: Fix security vulnerabilities in project modules

---

src/app/service-box/service-box.component.ts

Fixed issue of service box from parent issue #738 
**Link to live demo: ** http://pr-739-fossasia-loklaksearch.surge.sh

Parent #738:Fixed issue of service box.

---

src/app/actions/title.ts
src/app/app.module.ts
src/app/effects/api-search.effects.ts
src/app/effects/index.ts
src/app/effects/title.effects.ts
src/app/feed/feed.component.ts
src/app/home/home.component.spec.ts
src/app/home/home.component.ts
src/app/reducers/index.ts
src/app/reducers/title.ts

- Changes made to fix ```Title changing to since:day``` at homepage.
**Link to live demo: http://pr-747-fossasia-loklaksearch.surge.sh** 
**Closes #743**

Fixes #743: Create Action, Reducer and Effect for changing Title

---

.travis.yml

- Updates deployment link for development branch on surge to: http://loklak.surge.sh
- Updates the lcoal directory to deploy on surge.
**Screenshots (if appropriate)**  Not applicable.
**Link to live demo: http://pr-751-fossasia-loklaksearch.surge.sh**
**Closes #750**

Fixes #750: Complete development branch deployment on surge

---

src/app/home/home.component.html
src/app/home/home.component.spec.ts
src/app/home/home.component.ts

- Made changes to display results for only non empty query when user clicks enter after writing query on Home Page of loklak search.
**Link to live demo: http://pr-763-fossasia-loklaksearch.surge.sh** 
**Closes #759**

Fixes #759: Show results on clicking Enter after writing non empty query on Home Page

---

angular.json
src/styles/partials/_material-generic.scss

- Fixes material property of Tools and Views Tab to make it work as before.
- Fixes position of suggestion box (mat-autocomplete property).
- There is some issue with width and it will be solved in further patches.
**Link to live demo: http://pr-771-fossasia-loklaksearch.surge.sh** 
**Closes #**
Parent Issue: #758

Addresses #758: Fix Tools & Views tab and position of Suggestion Box

---

src/app/feed/info-box/info-box.component.html
src/app/feed/info-box/info-box.component.ts

- Fix broken images on sidebar widget.
- Start showing the top mentions on sidebar widget.
**Link to live demo: http://pr-780-fossasia-loklaksearch.surge.sh** 
**Closes #757**

Fixes #757: Fix broken images on sidebar widget

---

README.md

- Added Codacy label to the project README
**Link to live demo: http://pr-783-fossasia-loklaksearch.surge.sh**
**Closes #782**

Fixes #782: Add Codacy label to the project README

---

src/karma.conf.js

- Fixed Codacy issues in Karma.conf.js file.
**Link to live demo: http://pr-786-fossasia-loklaksearch.surge.sh** 
**Closes #785**

Fixes #785: Fix Codacy issues to merge development into master

---

.travis.yml

- Fixed travis to push changes from master to gh-pages branch on merging development into master.
**Link to live demo: http://pr-788-fossasia-loklaksearch.surge.sh** 
**Closes #787**

Fixes #787: Fix travis to push master to gh-pages branch

---

.travis.yml

- Merging development into master branch.

Merge development into master branch.

---

deploy.sh
package-lock.json
package.json

- Fixed yarn test (```Unknown option: '--reporters'```).
- Fixed security vulnerabilities.
- Fixed deployment to gh-pages branch from master through deploy.sh script.
**Link to live demo: http://pr-777-fossasia-loklaksearch.surge.sh** 
**Closes #776**

Fixes #776: Fix deployment to gh-pages and travis issues

---

docs/project/directory_structure.md

- Added docs folder to contain all the documentation for features added into the project.
- Initialised the docs with project directory structure.
**Link to live demo: http://pr-792-fossasia-loklaksearch.surge.sh** 
**Closes #791**
Parent Issue: #503

Fixes #791: Add docs for documentation and initialise project directory structure

---

src/app/home/home.component.html
src/app/home/home.component.scss

- Fixed floating trending bottom-hashtags on home page
**Link to live demo: http://pr-798-fossasia-loklaksearch.surge.sh**
**Closes #797**

Fixes #797: Fix floating trending bottom-hashtags on home page

---

src/app/feed/info-box/info-box.component.html
src/app/feed/info-box/info-box.component.ts

- Fixes CORB issues and broken images on chrome for sidebar infobox.
**Link to live demo: http://pr-796-fossasia-loklaksearch.surge.sh** 
**Closes #793**

Fixes #793: Fix CORB issue for sidebar infobox images on Chrome

---

src/app/services/auth.service.ts

- Created new apps for ```loklak-search``` on Facebook and Github.
- Setup new auth providers - Facebook, Github, Google, Email/Password.
**Link to live demo: http://pr-801-fossasia-loklaksearch.surge.sh**
**Closes #800**

Fixes #800: Setup new firebase auth providers - Facebook, Github, Google, Email/Password

---

.travis.yml
package-lock.json
package.json

- Fixed npm install error due in package-lock.json.
**Link to live demo: http://pr-815-fossasia-loklaksearch.surge.sh**
**Closes #814**

Fixes #814: Error in npm sha due to security vulnerability fix

---

src/app/effects/api-search.effects.ts
src/app/services/config/search-service.config.ts
src/app/services/search.service.ts

- Increase results count upto 100.
- Removed aggregation list.
**Link to live demo: http://pr-819-fossasia-loklaksearch.surge.sh**
**Closes #816**
Check the no of results by searching any query e.g. ```trump```.

Fixes #816: Increase results count upto 100

---

src/app/feed/info-box/info-box.component.ts

- Fixes repeated sidebar info-box's top twitters list.
**Link to live demo: http://pr-818-fossasia-loklaksearch.surge.sh**
**Closes #817**

Fixes #817: Fix repeated top twitters in sidebar info-box

---

src/app/feed/feed-advanced-search/feed-advanced-search.component.scss
src/app/feed/feed-header/feed-header.component.html
src/app/feed/feed-header/feed-header.component.scss

- Fixed width of auto complete suggestion box on results page.
**Link to live demo: http://pr-823-fossasia-loklaksearch.surge.sh**
**Closes #**
Addresses: #758

Addresses #758: Fix width and positon of auto complete mat box on results page

---

src/app/effects/api-user-search.effects.ts
src/app/feed/user-info-box/user-info-box.component.html

- Fixed CORB error for images of sidebar user-info-box.
- Provided default image for blocked or temporarily unavailable accounts.
**Link to live demo: http://pr-827-fossasia-loklaksearch.surge.sh**
**Closes #812**

Fixes #812: Implement user-info-box images to fix some broken images

---

package-lock.json
package.json

- Fix media wall component to display by updating angular material module.
**Link to live demo: http://pr-829-fossasia-loklaksearch.surge.sh**
**Closes #828**

Fixes #828: Fix Media-wall component to display

---

src/app/feed/info-box/info-box.component.html
src/app/feed/info-box/info-box.component.ts

- Sorted topMentions from largest to smallest.
- Fixed repetition of top mentions.
**Link to live demo: http://pr-826-fossasia-loklaksearch.surge.sh**
**Closes #820**

Fixes #820: Fix Repeated top mentions in sidebar info-box

---

src/app/feed/info-box/info-box.component.ts

- Made a new method for repeated code to parse data to sort and filter to get data sliced and sorted on basis of frequency of each unique key.
**Link to live demo: http://pr-837-fossasia-loklaksearch.surge.sh**
**Closes #836**

Fixes #836: Create new method for repeated code in sidebar info-box

---

src/app/home/home.component.scss

- Made changes to align bottom-list hashtags center with top-list hashtags on main page of loklak.
**Link to live demo: http://pr-840-fossasia-loklaksearch.surge.sh**
**Closes #839**

Fixes #839: Align bottom hashtags center with top hashtags

---

src/app/feed/user-info-box/user-info-box.component.html

- Fix error of accessing location of undefined in user-info-box.
**Link to live demo: http://pr-842-fossasia-loklaksearch.surge.sh**
**Closes #841**

Fixes #841: Fix can't read location of undefined error

---

src/app/services/search.service.ts
src/app/utils/reg-exp.ts

- Added new hashtag and mention reg exp to check query type.
- Made changes to update search API URL based on the type of query param.
**Link to live demo: http://pr-848-fossasia-loklaksearch.surge.sh**
**Closes #847**

Fixes #847: Change search API URL based on type of parameter of query

---

src/app/services/user.service.spec.ts
src/app/services/user.service.ts

- Written new test file for UserService.
**Link to live demo: http://pr-851-fossasia-loklaksearch.surge.sh**
**Closes #850**

Fixes #850: Write new test file for UserService

---

src/app/utils/reg-exp.spec.ts

- Written tests for new reg-exp to increase test coverage.
**Link to live demo: http://pr-853-fossasia-loklaksearch.surge.sh**
**Closes #852**

Fixes #852: Write tests for new reg-exp to increase test coverage

---

src/app/feed/info-box/info-box.component.html
src/app/feed/info-box/info-box.component.ts

- Made changes to change search api url for json and rss feed based on type of query param.
**Link to live demo: http://pr-855-fossasia-loklaksearch.surge.sh**
**Closes #854**

Fixes #854: search api url for json and rss feed should change

---

src/app/feed/info-box/info-box.component.ts

- Made changes to not show the query hashtag in Top Hashtags section.
**Link to live demo: http://pr-856-fossasia-loklaksearch.surge.sh**
**Closes #846**

Fixes #846: Top Hashtags should not contain the query hashtag

---

src/app/feed/info-box/info-box.component.ts

- Fixed top mentions to not contain query mention.
**Link to live demo: http://pr-860-fossasia-loklaksearch.surge.sh**
**Closes #857**

Fixes #857: Top mentions should not contain the query mention

---

src/app/privacy/privacy.component.spec.ts
src/app/speech/speech.component.spec.ts
src/app/speech/speech.component.ts
src/app/terms/terms.component.spec.ts

- Fixed test files to make each test unit unique. Earlier About, Terms, and Privacy tests were not possible to distinguish.
**Link to live demo: http://pr-859-fossasia-loklaksearch.surge.sh**
**Closes #858**

Fixes #858: Fix test files to make each test unit unique

---

src/app/services/config/search-service.config.ts

- Reduced load time and increased speed of UI by decreasing count of results from 100 to normal.
**Link to live demo: http://pr-867-fossasia-loklaksearch.surge.sh**
**Closes #866*

Fixes #866: Fix results count from 100 to normal

---

src/app/feed/feed-footer/feed-footer.component.html
src/app/feed/feed-user-card/feed-user-card.component.html

- Fix console errors for sorted api response in feed-footer, and feed-user-card.
**Link to live demo: http://pr-871-fossasia-loklaksearch.surge.sh** 
Parent issue: #865
**Closes #**

Addresses #865: Fix console errors

---

src/app/models/query.spec.ts
src/app/models/query.ts
src/app/services/search.service.ts

- Added query param for ```near``` in search service and added respective argument of ```q``` in api URL. 
**Link to live demo: http://pr-892-fossasia-loklaksearch.surge.sh**
**Closes #891**

Addresses #891: Add 'near' param for query of location based search

---

package-lock.json
package.json
src/app/app-routing.module.ts
src/app/feed/feed-advanced-search/feed-advanced-search.component.html
src/app/feed/feed-advanced-search/feed-advanced-search.component.scss
src/app/feed/feed-news/feed-news.component.html
src/app/feed/feed-news/feed-news.component.ts
src/app/models/query.spec.ts
src/app/models/query.ts
src/app/services/config/search-service.config.ts
src/app/services/search.service.ts
src/app/settings/settings-routing.module.ts
src/app/settings/settings.component.html
src/app/settings/settings.component.scss
src/app/settings/settings.component.spec.ts
src/app/settings/settings.component.ts
src/app/settings/settings.module.ts
src/app/shared/news-org.ts

- Merge development into master branch.

Loklak Search Release 3

---

src/app/home/home.component.scss
src/app/service-box/service-box.component.scss

- Fixed movement of search box on loading of hashtags on start page of loklak_search. 
- Fixed responsiveness of 9-dot menu for screens appx > 320px.
**Link to live demo: http://pr-893-fossasia-loklaksearch.surge.sh**
**Closes #863**

Fixes #863: Loading of hashtags on start page moves up search box

---

src/app/feed/feed-advanced-search/feed-advanced-search.component.html
src/app/feed/feed-advanced-search/feed-advanced-search.component.scss
src/app/feed/feed.component.scss
src/app/feed/info-box/info-box.component.html
src/app/feed/info-box/info-box.component.scss
src/app/service-box/service-box.component.scss

- Made responsive in small screen resolutions.
**Link to live demo: http://pr-799-fossasia-loklaksearch.surge.sh**
**Closes #795**

Fixes #795: Make responsive in smaller devices

---

src/app/services/search.service.ts
src/app/services/suggest.service.ts

- Fixed the irrelevant results issue for hashtag query.
- Fixed the irrelevant & null suggestion results for hashtag query.
- Fixed console errors.
**Link to live demo: http://pr-896-fossasia-loklaksearch.surge.sh**
**Closes #865**
**Closes #895**

Fixes #895, #865: Fix results for hashtag query and console errors

---

src/app/feed/feed-advanced-search/feed-advanced-search.component.html
src/app/feed/feed-advanced-search/feed-advanced-search.component.scss
src/app/feed/feed-news/feed-news.component.html
src/app/feed/feed-news/feed-news.component.scss
src/app/feed/feed-news/feed-news.component.ts
src/app/feed/feed.component.html
src/app/feed/feed.component.scss
src/app/feed/feed.component.ts
src/app/feed/info-box/info-box.component.html
src/app/feed/info-box/info-box.component.scss
src/app/home/home.component.scss
src/app/service-box/service-box.component.scss
src/app/services/search.service.ts
src/app/services/suggest.service.ts
src/app/shared/url-config.ts

- Merging development branch into master branch for 4th stable release of loklak.

Loklak Search Release 4
