src/app/about/about.component.html
src/app/about/about.component.scss
src/app/contact/contact.component.html
src/app/contact/contact.component.scss
src/app/footer/footer.component.scss

Mobile Responsiveness
Space above the gray bar on all screens and the bar on the bottom of the page in search page (#81 issue)

#83 #69 &#81 fixed

---

src/app/feed/feed-card/feed-card.component.html
src/app/feed/feed-card/feed-card.component.ts

* Hashtags are now linking internally.
* This uses simple redirect to the new page with new query
* This is a temporary fix as autolinker.js replaceFn doesn't play well with angular
* We might need to write our own parsing linking module in future to make the things look more asynchronous.

Fixes #88: Hashtags linking internally

---

src/app/feed/feed-card/feed-card.component.ts
src/index.html

* All `@<username>` mentions are now redirecting to the the results page.
* This page shows the result of the query `from:<username>`

Fixes #98 : mentions redirecting to results-page

---

package.json
src/app/feed/feed-card/feed-card.component.html
src/app/feed/feed-card/feed-card.component.ts
src/app/feed/feed-linker/feed-linker.component.html
src/app/feed/feed-linker/feed-linker.component.spec.ts
src/app/feed/feed-linker/feed-linker.component.ts
src/app/feed/feed.component.spec.ts
src/app/feed/feed.module.ts
src/app/shared/classes/search/api-response.ts
src/app/shared/configrations/autolinker.config.ts
src/app/shared/configrations/index.ts
src/app/shared/index.ts

* Asynchronous linking module, for hashtags and mentions.
* URL mapping with the use of unshorten property of the object.
[NOTE]:
* This only redirects the user to the respective query search and
* Actual searching is not yet implemented
* Because actual searching will make this commit very complex and a lot of file changes and ground up modificaions will be required.
* To handle this currently there is a force reload of the page on every click on "mention" and "hashtags" but this can be removed as soon as the functionality of handling query searches is implemented using `ngrx/store` based approach. (Another prominent need of REDUX based architecture).

Fixes #108,#97 : Linking module implementation.

---

src/app/feed/feed-card/feed-card.component.ts

* It seems that if `unshorten` property is absent in the `ApiResponse` app (linker component) breaks down.
* Fixed by setting `link_to` in config either unshorten property or blank object `{}` if that property is absent
* It is still unclear to me why in some cases the `unshorten` property is not present.

Fixes #116: Preventing app breakdown

---

README.md

README.md edited.
Requirement and How to deploy section added.
Installation section fixed.

Improvement in Documentation

---

src/app/feed/feed-footer/feed-footer.component.html
src/app/feed/feed-footer/feed-footer.component.scss
src/app/feed/feed-footer/feed-footer.component.spec.ts
src/app/feed/feed-footer/feed-footer.component.ts
src/app/feed/feed.component.html
src/app/feed/feed.component.spec.ts
src/app/feed/feed.module.ts

*Collect hashtags from the search results in decreasing order of frequency
*Display top 10 hashtags in the feed-footer

Fixes #42: Add related hashtags component

---

src/app/about/about.component.html
src/app/about/about.module.ts
src/app/contact/contact.component.html
src/app/contact/contact.module.ts
src/app/terms/terms.component.html
src/app/terms/terms.module.ts

Initially :- The app used navigation in navbar to different page options as "href"(external link navigation) which caused app to reload the app and retrieve the app data. 
Now :- To avoid reloading of app , routerlink directive has been introduced in the navbar to provide internal routing system in app. This will improve performance of the app.
Kindly check.

Navigation bar link improvement

---

src/app/app.component.spec.ts
src/app/app.component.ts

Problem with routerLink is that suppose you route to some other page then it doesn't scroll to top and it shows up the new page with the scroll position as the previous one.
Now the pages linked in the bottom menu will route to the top .
gh-pages- https://achint08.github.io/loklak_search/
Kindly check and review :)

Fixes #85 : bottom menu item links to top

---

src/app/feed/feed-pagination/feed-pagination.component.html
src/app/feed/feed-pagination/feed-pagination.component.scss
src/app/feed/feed-pagination/feed-pagination.component.ts
src/app/feed/feed.component.html
src/app/feed/feed.component.spec.ts
src/app/feed/feed.component.ts
src/app/reducers/index.ts
src/app/reducers/pagination.ts

- Show loading icon after user clicks on "Show More"
- Show "Search More" only when more results are available
It has been implemented as "Show More" is not shown if the previous search request did not return the maximum records i.e set to 30.
Screenshot during loading.
Link for live testing : https://uttu357.github.io/loklak_search/
Closes #164 #176

Fix #164 #176

---

404.html

Now the redirect is to `loklak.net` instead of `loklak.fossasia.org` in 404.html

Fixes #192: Changing 404.html

---

src/app/feed/feed.component.scss
src/app/footer/footer.component.scss

-Also reduces the container size to account for footer so that there is no scroll when there are no results.
Closes #69

Fix #69: Adds responsive top margin

---

src/app/feed/feed-header/feed-header.component.scss
src/app/feed/feed.component.scss
src/app/feed/info-box/info-box.component.html
src/app/feed/info-box/info-box.component.scss
src/app/home/home.component.scss
src/styles/partials/_theme.scss

- Width of tweet content area set to be same as search bar
- Increase distance from upper gray menu bar
- Reduce the space between blue profile icons and the info
- Width of areas set to stay the same on change of resolution
Changes live at https://uttu357.github.io/loklak_search/search?query=hello
Closes #206 #196

Fix #206 #196 : Feed Results styling

---

src/app/app.module.ts
src/app/pagenotfound/pagenotfound-routing.module.ts
src/app/pagenotfound/pagenotfound.component.html
src/app/pagenotfound/pagenotfound.component.scss
src/app/pagenotfound/pagenotfound.component.spec.ts
src/app/pagenotfound/pagenotfound.component.ts
src/app/pagenotfound/pagenotfound.module.ts

Kindly check and review. 
gh-pages- https://achint08.github.io/loklak_search/

Fixes #219 : 404 page

---

src/app/reducers/api-response.ts
src/app/reducers/pagination.ts

Fixes #231 .
Previously there was an error message because new API Response Aggregations sometimes returned null when there were no new tweet feeds on clicking "Show more"  due to which search service crashed. The error is shown below :-
You can come across the error by searching for some queries(Keep a check on console meanwhile) on loklak.net .Now click on "Show more" for new tweets. Try this for 2-3 queries. You will come across this error sometimes.
What I did is that in case api response  aggregation is returned null , I have set the previous aggregation to the new aggregation. Now the variable statistics in the info box component will not be undefined anytime.
I also changed boolean variable conditional operation from 30 to 20. The reason being previously I changed number of …

Fixes #231 :- error clear

---

src/app/feed/info-box/info-box.component.html

Previously the request for profile images was retrieving large pictures that too in png format.(somewhat around 512 x 512)
Now the request for profile images will be smaller and in jpeg format.(48 x 48)
This is improving site speed as we are retrieving approximately 20 images for the info-box so smaller images and jpeg format will enhance our site speed .
Checkout my gh-pages [here](https://achint08.github.io/loklak_search/)

Fixes  #239 :- Retrieving smaller images

---

src/app/footer/footer.component.scss

left aligned the items
Now the footer takes up two lines in mobile version and all the items
are left aligned

fixes #247 - reduced empty space taken by footer in mobile version and

---

src/app/feed/feed.component.scss

Width of info-box is 100% on phones.
Closes #248

Fix #248: Fix width of info-box on phones

---

src/app/feed/feed-header/feed-header.component.scss
src/app/feed/info-box/info-box.component.html
src/app/footer/footer.component.scss
src/app/home/home.component.scss

1. This fixes the problem of having the footer in 2 lines in #247.
2. This also fixes the issue of having `cursor:text` in the input box and the button with `cursor:pointer` in issue #230 
3. This commit also fixes the header design as listed in the description of #257. 
View the demo [here.](http://rishiraj.co/loklak_search/)
@mariobehling Please check :)

Fixes #247, #230 and #257

---

src/app/effects/api-search.effects.ts
src/app/feed/feed.component.ts

**Fixes #264 :  Resolved bug**
Now the search parameters will be converted to URI standardized form. i.e.
If you search for #Openevent , the link
will be encoded to 
http://loklak.net/search?query=%23Openevent
(this link will work to show results for #Openevent)
that is the standardized form so that search url can be used as a link to show results of "#Openevent".
Previously , the back option was also not working for search results. Now It will work.
**Link to live demo (if appropriate):**
Live link [here](https://achint08.github.io/loklak_search/) 
**Closes #264 **
Kindly review and correct me :)
@mariobehling Will this Serve the purpose?

Fixes #264 :Resolved bug

---

src/app/actions/api.ts
src/app/app.module.ts
src/app/effects/api-aggregation.effects.ts
src/app/feed/feed.component.ts
src/app/reducers/api-response.ts
src/app/services/aggregation.service.spec.ts
src/app/services/aggregation.service.ts
src/app/services/index.ts

**Fixes #270 ,#271 , #272 , #254  : Implements seperate API request for Aggregation**
Separate request for aggregations have been made to get aggregation and avoid search service crash.
Now the aggregation service will work again and 
-> Side Bar will work again
-> Show more will work.
-> Pagination will work properly
Checkout [here](https://achint08.github.io/loklak_search/).
**Closes #270 , #271 , #272, #254  **

Fixes #270 , #271 , #272 #254 : API request for aggregation

---

src/app/feed/feed-lightbox/feed-lightbox.component.html

- Open in twitter link will open only one tab
**Link to live demo (if appropriate):https://uttu357.github.io/loklak_search/search?query=from%3Aheroku** 
**Closes #266**

Fix #266: Fixes "Open in Twitter" link

---

src/app/feed/feed.component.html

- Hide show more when all the followers are loaded.
**Link to live demo (if appropriate):https://uttu357.github.io/loklak_search/search?query=followers:Achintsharma08** 
**Closes #296**

fix(followers-pagination): Hide show more

---

deploy.sh
package.json
src/app/app.component.spec.ts
src/testing/router-stubs.ts

Production mode enabled in deployment,
* shrinks vendor.js (1.1M)
* shrinks main.js (450K)
* shrinks styles.js (25K)
**Closes #305**

(Build)Fixes #305: Production mode in deployment

---

src/app/feed/feed-header/feed-header.component.scss

- Color of the search bar wrapper changed to #fafafa as the market leader.
**Screenshots** 
**Closes #320**
**Link** - [rishiraj824.github.io/loklak_search](http://rishiraj.co/loklak_search)

Fixes #320: Match distance above search bar on pages to market leader

---

src/app/feed/info-box/info-box.component.html
src/app/feed/info-box/info-box.component.ts

- Hides InfoBox Columns when there is no data available
- Hides InfoBox when no column is available
**Screenshots** 
- **Hides Respective Columns when no data available for eg, here Top Mentions**
- **Hides the InfoBox when no data is available at all**
**Link to live demo:** 
[rishiraj.co/loklak_search](http://rishiraj.co/loklak_search)
**Closes #322 & #324**

Fixes #322 & #324: Hide InfoBox Content when no results available

---

package.json

- Fix angular material version to 2.0.0-beta.2
beta.3 moved to Angular 4 and hence it results in crashing of our application as it still depends on Angular 2.4.10. Hence when we update to Angular 4 we can update Angular material but not at present.

Fix version of angular/material dependency to beta-2

---

src/app/feed/feed.component.scss

Issue No.  #343 
Decrease the size of the search string and align it to the centre. 
**Related pic:** 
**PR's Fix:** 
````
.searching-message { 
word-break: break-word; 
font-size: 2em; 
font-size: 1.5em; 
text-align: center; 
padding: 10px; 
margin: 0 23%; 
} 
````

Fix #343: Searching text is not aligned in the center and is too large on small screens

---

src/app/home/home.component.scss

- Safari , by default , assumes element to be in the center. Made app-footer element shifted to the left.
-
-
**Closes #**

Fixes #336 :- Corrects Footer navigation bar

---

README.md
src/app/app.module.ts

* Store Devtools module is now disabled by default. 
* To enable it uncomment in the `imports` array of `app.module.ts`.
**Closes #365 **

Fixes #365: Store Devtools module disabled by default

---

.travis.yml
karma.conf.js
package.json

* Fixes the `codecov` error
**Closes #380**

Fixes #380: Generating coverage after tests.

---

README.md

The codecov was not refering to the correct branch thus showing the stale status.
This fixes the correct url
**Closes #384**

Fixes #384: Update url to refer to correct branch in codecov

---

codecov.yml

CodeCov reports to show up in dashboard of CodeCov site.

(chore):Change default CodeCov branch to master

---

src/app/actions/query.ts
src/app/effects/api-search.effects.spec.ts
src/app/effects/api-search.effects.ts
src/app/effects/api-suggest.effects.spec.ts
src/app/effects/api-suggest.effects.ts
src/app/effects/api-user-search.effects.spec.ts
src/app/effects/api-user-search.effects.ts
src/app/effects/pagination.effects.spec.ts
src/app/effects/pagination.effects.ts
src/app/effects/query.effects.ts
src/app/feed/feed.component.ts
src/app/feed/info-box/info-box.component.ts
src/app/home/home.component.ts
src/app/models/query.ts
src/app/reducers/query.ts
src/app/reducers/search.spec.ts
src/app/reducers/search.ts
src/app/reducers/suggest.spec.ts
src/app/shared/mocks/feedItem.mock.ts

* Cleans up the code
* Use `interface extension` instead of dirty copying all the properties from the model to state
**Test link:** https://hemantjadon.github.io/loklak_search
**Closes #406**

Relocation after query separate from query model

---

src/app/models/query.spec.ts
src/app/models/query.ts
src/app/reducers/query.ts
src/app/utils/date-time.spec.ts
src/app/utils/date-time.ts
src/app/utils/index.ts

* This fixes up the querystring generation from the URL
* Included the unit tests for the proper testing
* Does not include for the `media filters`.
**Closes #409**

Fixes #409: Query Parser funtion to get query string from query

---

src/app/effects/api-search.effects.ts
src/app/effects/pagination.effects.ts
src/app/models/filters.ts
src/app/models/query.spec.ts
src/app/models/query.ts
src/app/reducers/index.ts
src/app/reducers/media-wall.ts
src/app/reducers/query.ts
src/app/services/config/index.ts
src/app/services/config/search-service.config.ts
src/app/services/index.ts
src/app/services/search.service.spec.ts
src/app/services/search.service.ts
src/app/shared/mocks/feedItem.mock.ts

* The ability to get a default state and customize the other parts at will.
**Closes #425**

Search service customization for better control over query params of request

---

src/app/home/home.component.html

Number of hashtags on the homepage increased from 5 to 9
**Closes #466**

Increase number of hashtags on home page

---

src/app/feed/feed-advanced-search/feed-advanced-search.component.scss

Fixing the bug of ability to access the feed advanced search tools even if it is hidden
**Closes #476**

Feed advanced search tools inactive on hide

---

src/app/home/home.component.html
src/app/home/home.component.scss

* Multiline error fix for non-english words
* Truncate long hashtags (beyond 100px wide)
* Fix the flex issue of overflowing list
**Closes #492**

Top hashtag breaking UI fix

---

src/app/feed/feed-advanced-search/feed-advanced-search.component.html
src/app/feed/feed.component.scss

* Matches the gap between the feed strip and the top header to "Market Leader"
* Remove the message "Loklak Scrapes ... "
https://hemantjadon.github.io/loklak_search/
**Closes #539**

Matching gap between feed and header

---

src/app/home/home.component.scss

The ellipsis are removed from the trending hashtags. This shows the entire text and the width in which they are shown is also maintained
**Closes #**
#545

Removed ellipsis from the trending hashtags

---

src/app/app-routing.module.ts
src/app/footer/footer.component.html
src/app/privacy/privacy-routing.module.ts
src/app/privacy/privacy.component.html
src/app/privacy/privacy.component.scss
src/app/privacy/privacy.component.spec.ts
src/app/privacy/privacy.component.ts
src/app/privacy/privacy.module.ts

- I have added a privacy page and linked it in the footer.
**Closes #554 **

Fixes #554 : Add "Privacy" Page and link it in Footer

---

src/app/feed/feed-header/feed-header.component.scss

- Now search icon is not displaced.
[Please see the gh pages deployment ](https://parths007.github.io/loklak_search/)
**Closes #588

Fixes #588 Search box displays search button wrongly on Firefox

---

src/app/privacy/privacy.component.html
src/app/terms/terms.component.html

**Changes proposed in this pull request:**
- Added link to the contact page in the last line of privacy and terms page.
**Screenshots (if appropriate):** 
[Demo Link.](https://marvin08.github.io/loklak_search/)
**Closes #622.**

Fixes #622: Added link to contact page in the bottom of privacy and terms page

---

src/app/home/home.component.ts
src/app/speech.service.ts

- Made changes to stop speech propagation when results are shown, until the user explicitly clicks voice search next time.
**Link to live demo: http://profuse-rainstorm.surge.sh/** 
**Closes #674**
@mariobehling @singhpratyush please review.

Fixed #674: Stop(deactivate) voice search when completed

---

src/app/media-wall/media-wall-design/media-wall-design.component.scss
src/app/media-wall/media-wall-moderation/media-wall-moderation.component.scss
src/app/media-wall/media-wall-query/media-wall-query.component.scss

user doesn't have to scroll to top to close any window in media wall.
**Screenshots**
**Before**
**After**
**Link to live demo:  http://pr-685-fossasia-loklaksearch.surge.sh** 
**Closes #682**
@singhpratyush please review.

Fix the close button

---

src/app/services/search.service.ts

- The 404 error was getting displayed in some images because the API returned an array of images for those tweets which have multiple images and that wasn't being handled properly, so that bug has been fixed here and the first image is shown for such tweets
BEFORE
AFTER
**Addresses #688**

404 image error

---

src/app/feed/feed-footer/feed-footer.component.html

- Solves problem of displaying of empty hashtags returned.
- Adds user help text when 0 hashtags are returned.
---
---
**Link to live demo: http://pr-719-fossasia-loklaksearch.surge.sh** 
**Closes #718**

Fixes #718: Do not show empty hashtags and add user help text

---

angular.json

- Made changes to fix UI bugs in development.
- Made changes to support host listener decorator.
- Fixes part of parent issue - #738
**Link to live demo:http://pr-740-fossasia-loklaksearch.surge.sh** 
**Closes #**

Parent #738: Fix CSS issues in development

---

README.md

- Fixed Gemnasium dependency label.
- Added different labels for travis build for development and master branch.
- Updated technology stack(Current Angular version).
- Include new required labels - issue resolution, opened issue %.
**Link to live demo: http://pr-752-fossasia-loklaksearch.surge.sh** 
**Closes #712**
**Closes #748**

Fixes #748, #712: Add label for travis build and fix Gemnasium dependency label

---

src/app/feed/feed.component.html
src/app/feed/feed.component.spec.ts
src/app/feed/feed.component.ts
src/app/feed/info-box/info-box.component.html
src/app/feed/info-box/info-box.component.ts
src/app/reducers/index.ts
src/app/services/search.service.ts

- Created new source for sidebar results. The older config was not getting results.
- Removed Trending hashtags from results page.
- Added more parameters to ```api/search.json``` to provide filtered search.
- Added source to be apiResponseResults from parent feed.component.ts to child feed-info.component.ts.
The changes have been made and it looks more appropriate in live test link.
**Link to live demo: http://pr-754-fossasia-loklaksearch.surge.sh** 
**Closes #188**
**Closes #333**
**Closes #543**
**Note:** Work is being carried out currently to show images on sidebar (The older implementation was trying to fetch images from twitter which do not works due to twitter updates).

Fixes #188, #333, #543: Fix missing sidebar and improve results

---

src/app/feed/info-box/info-box.component.html
src/app/feed/info-box/info-box.component.ts
src/app/feed/user-info-box/user-info-box.component.html

- Fixed console error for user-info with no description.
- Fixed repeated top twitter and top mentions from sidebar.
- There are some hashtags which seems to be repeated but they are actually the first elements of array (may contain different elements). It will be fixed with images of sidebar.
- Updated the router link queries for sidebar users.
**Link to live demo: http://pr-756-fossasia-loklaksearch.surge.sh** 
**Closes #755**
Parent Issue: #716

Fixes #755: Repeating data in sidebar, and Adress: #716 console errors

---

src/app/effects/api-search.effects.ts
src/app/media-wall/media-wall.component.ts

- Removed Effect method to only set Media-Wall title (Removed additional load).
- Used already existing Title Action to set Media-Wall title.
- Removed unused imports and declarations.
**Link to live demo: http://pr-762-fossasia-loklaksearch.surge.sh** 
**Closes #761**

Fixes #761: Use Title Action to set Media-Wall title

---

src/app/utils/reg-exp.spec.ts

- Added new test case file for reg-exp utility function.
- 13 new test units are added. Now total test units are: 170+13 = 183.
**Link to live demo: http://pr-765-fossasia-loklaksearch.surge.sh** 
**Closes #764**

Fixes #764: Add new test for reg-exp utility to increase test coverage

---

src/app/feed/feed-header/feed-header.component.scss
src/app/service-box/service-box.component.html
src/app/service-box/service-box.component.scss

- Fixed Service Box mat property and adjusted its position.
- Made it to white on home page.
- Fixed its color on results page.
- It acquires background color of page.
**Link to live demo: http://pr-769-fossasia-loklaksearch.surge.sh**
**Closes #**
Parent Issue: #758

Addresses #758: Fix Service Box display mat property

---

Dockerfile
src/karma.conf.js

- Fixed deprecated ```MAINTAINER``` from docker file.
- Used double quotes in karma.conf.js.
- Used single quotes to prevent word splitting in docker file run command.
**Link to live demo: http://pr-775-fossasia-loklaksearch.surge.sh**
**Closes #774**

Fixes #774: Fix Codacy issues

---

src/app/about/about.component.spec.ts
src/app/about/about.component.ts
src/app/contact/contact.component.spec.ts
src/app/contact/contact.component.ts
src/app/effects/title.effects.ts
src/app/pagenotfound/pagenotfound.component.spec.ts
src/app/pagenotfound/pagenotfound.component.ts
src/app/privacy/privacy.component.spec.ts
src/app/privacy/privacy.component.ts
src/app/terms/terms.component.spec.ts
src/app/terms/terms.component.ts

- Removed all instances from each component which were using angular browser's Title property to set title of corresponding webpages.
- Used already created Title Action to set the respective title.
Separate work is being carried out to write tests for the project.
**Link to live demo: http://pr-773-fossasia-loklaksearch.surge.sh** 
**Closes #772**

Fixes #772: Replace all instance of Title property with titleAction

---

package-lock.json

- Updated Integrity sha1 value in package-lock.json required for dev deployment on surge.
**Link to live demo: http://pr-779-fossasia-loklaksearch.surge.sh** 
**Closes #778**

Fixes #778: Update Integrity sha1 value

---

src/app/feed/user-info-box/user-info-box.component.html
src/app/feed/user-info-box/user-info-box.component.scss

- Fixes followers and following images on sidebar user-info-box. 
**Link to live demo: http://pr-781-fossasia-loklaksearch.surge.sh**
---
---
**Closes #360**
**Closes #653**
**Closes #690**
Addresses parent issue: #716

Fixes: #360, #653,  #690, #716: Fix broken images on user-info-box

---

.travis.yml
package-lock.json
package.json

- Fixed security vulnerabilities from project dependencies.
- Removed Yarn from travis.
- Updated node and npm version and set new npm registry since older one was leading to project Integrity checksum failed error for SHA values. 
**Link to live demo: http://pr-807-fossasia-loklaksearch.surge.sh**
**Closes #806**

Fixes #806: Fix security vulnerabilities and remove yarn from travis

---

src/app/feed/user-info-box/user-info-box.component.html

- Keep proper spacing between heading and text in user-info-box.
**Link to live demo: http://pr-825-fossasia-loklaksearch.surge.sh** 
**Closes #**
Addresses: #433, #810.

Adresses #810, #433: Keep space between heading and text in user-info-box

---

src/app/feed/info-box/info-box.component.html
src/app/feed/info-box/info-box.component.ts

- Sorted top trending hashtags from most to least.
- Fixed repetition.
- Filtered invalid hashtags, and displayed correct count for hashtags.
**Link to live demo: http://pr-831-fossasia-loklaksearch.surge.sh**
**Closes #830**

Fixes #830: Fix repeated top hashtags with incorrect count of hashtags in sidebar

---

src/app/about/about.component.spec.ts

- Added 7 new test units to About Component.
- Now Total test units: 173 + 7 = 180
**Link to live demo: http://pr-834-fossasia-loklaksearch.surge.sh**
**Closes #833**

Fixes #833: Add new test units for About Component

---

src/app/home/home.component.html

- Fixed error on console when no trending hashtags are returned because of server down.
**Link to live demo: http://pr-868-fossasia-loklaksearch.surge.sh**
Parent issue: #865
**Closes #**

Fixes #865: Fix errors on console when no  hashtags are returned

---

src/app/feed/feed.component.scss

- Made changes to remove the scrolling when the results are being loaded.
- Also made the footer to appear when results are being loaded.
**Screenshots (if appropriate)**
**Link to live demo: http://pr-870-fossasia-loklaksearch.surge.sh**
**Closes #869**

Fixes #869: Remove scrolling when loading results screen is displayed

---

src/app/feed/feed-advanced-search/feed-advanced-search.component.html
src/app/feed/feed-advanced-search/feed-advanced-search.component.scss

- Made hovering similar to Google tabs to contain color: ```#222``` on hover and selected tab's text should be bold as in Google tabs. 
- Removed unwanted outlines from tabs.
- Removed mat property from Tools and Views tabs to make it similar to other tabs and comparable to Google tabs.
- Now it looks more or like similar to market leader Google.
- Further work is being carried out to solve rest in next patch.
**Link to live demo: http://pr-872-fossasia-loklaksearch.surge.sh**
Addresses #861
**Closes #**

Addresses #861: Make tabs and effects similar to Google

---

src/app/about/about.component.html
src/app/about/about.component.ts
src/app/feed/feed-not-found/feed-not-found.component.html
src/app/feed/feed-not-found/feed-not-found.component.ts
src/app/feed/info-box/info-box.component.html
src/app/feed/info-box/info-box.component.ts
src/app/footer/footer.component.html
src/app/footer/footer.component.ts
src/app/service-box/service-box.component.html
src/app/service-box/service-box.component.ts
src/app/services/push.service.ts
src/app/services/search.service.ts
src/app/services/suggest.service.ts
src/app/services/user.service.ts
src/app/shared/index.ts
src/app/shared/mocks/userResponse.mock.ts
src/app/shared/url-config.ts

- Added ```url-config``` file inside ```/shared``` folder with all hardcoded URLs.
- Fetched the URLs from config file to use in all occurrences of the project.
- This structure can be modified and new URLs could be added inside the ```url-config``` file to be used inside the multiple instances.
- Currently two places are not using these URLs - README.md and index.html.
**Link to live demo: http://pr-875-fossasia-loklaksearch.surge.sh**
**Closes #874**

Fixes #874: Add hardcoded server URLs in a config file

---

src/app/feed/info-box/info-box.component.ts

- Fixed x-axis of tweets frequency graph on results page to display date on x-axis.
**Link to live demo: http://pr-881-fossasia-loklaksearch.surge.sh**
**Closes #880**

Fixes #880: Fix x-axis of tweets frequency graph on results page

---

src/app/feed/feed-news/feed-news.component.html
src/app/feed/feed-news/feed-news.component.ts
src/app/shared/news-org.ts

- Made changes to show only relevant query related results under news tab.
- Added new news organisations in news configuration file: ```CNNPolitics```, ```BBC```, ```guardian```, ```toi```.
- Added action, reducer for news search complete status.
**WIP**: Feed not found message needs to be added as a next step to display ```no results``` message when there are no matching content.
**Link to live demo: http://pr-890-fossasia-loklaksearch.surge.sh**
**Closes #862**

Fixes #862: Fix irrelevant results in news tab

---

src/app/feed/feed.component.html
src/app/feed/feed.component.ts

- Made changes to display User-info-box for queries which search for user and not for other queries.
**Link to live demo: http://pr-898-fossasia-loklaksearch.surge.sh**
**Closes #811**

Fixes #811: User info box should appear independent of the main feed results

---

src/app/feed/feed-news/feed-news.component.html
src/app/feed/feed-news/feed-news.component.scss
src/app/feed/feed-news/feed-news.component.ts
src/app/shared/url-config.ts

- Added info about no of results obtained in news.
- Added info about changing/updating the current file containing news orgs.
- Added hardcoded URL for the Github file containing the names of news orgs.
- Made the info architecture similar to Google: text-color, text-size, hover color. 
**Link to live demo: http://pr-897-fossasia-loklaksearch.surge.sh**
**Closes #873**

Fixes #873: Add info about News into news tab
